//
// Created by jadjer on 01.02.2026.
//

#ifndef SUBARUCARLINKADAPTER_AUDIOPROCESSOR_HPP
#define SUBARUCARLINKADAPTER_AUDIOPROCESSOR_HPP

class AudioProcessor {};

#endif // SUBARUCARLINKADAPTER_AUDIOPROCESSOR_HPP
